import Image from 'next/image'
import React from 'react'
import { GiFruitTree } from 'react-icons/gi'
import goals from '../../../../../styles/landing/goals.module.css'
import { GoGoal } from 'react-icons/go'

const Goals = () => {
  return (
    <section id='our-goals' className={goals.section_mainContainer}>
        <div>
            <section className={goals.section_innerSect}> 
                    <h2>Investment Objective</h2>
                <div>
                    <article>
                        <GiFruitTree className={goals.Icons} />
                        <h3>
                        Funding Growth and Expansion
                        </h3>
                        <p>
                        The primary goal of the DPO is to raise capital for the development and
                        <br />
                         expansion of sustainable energy projects across multiple regions.
                        </p>
                    </article>
                    <article>
                    <GiFruitTree className={goals.Icons} />
                        <h3>
                        Promoting Clean Energy Transition
                        </h3>
                        <p>
                        By investing in this offering, investors actively contribute to the global
                        <br />
                         transition towards clean and renewable energy sources.
                        </p>
                    </article>

                </div>
            </section>
            <section className={goals.section_innerSect}>
                    <h2>Return Potential</h2>
                <div>
                    <article>
                        <GoGoal className={goals.Icons} />
                        <h3>
                        Potential Capital Appreciation
                        </h3>
                        <p>
                        As the renewable energy sector continues to grow, investments in sustainable 
                        <br />
                        energy infrastructure have the potential to appreciate in value over time.
                        </p>
                    </article>
                    <article>
                    <GoGoal className={goals.Icons} />
                        <h3>
                        Dividend Distributions
                        </h3>
                        <p>
                        Investors may receive periodic dividend distributions from the cash flows
                        <br />
                         generated by the operational renewable energy projects.
                        </p>
                    </article>

                </div>
            </section>
        </div>
    </section>
  )
}

export default Goals